### ISSUE TITLE
scaling down issues

### ISSUE THREAD

**Issue by rosslutsch** [morphy2k/k8s-mongo-sidecar#41] opened 2020-01-13 19:08 UTC
When I start with 1 replicaset it becomes primary and everything works fine, I then add a few more members and the sidecar picks them up and adds them to the list but when I scale back downt the the members aren't being removed from the list and all members become secondary when there is no quorum to hold elections.

**Comment by MarsssBlkm** [comment] 2020-02-12 09:42
@rosslutsch Any information when you run `kubectl logs YOUR-POD-NAME mongo-sidecar`?

**Comment by rosslutsch** [comment] 2020-02-12 10:01
@MarsssBlkm here is what I understand so far.

  - With a member missing because of the scaling down the quorum is lost and it logs the following every few seconds

Pod has been elected as a secondary to do primary work
Pod has been elected as a secondary to do primary work
- as there is no primary all the remaining pods become slave
- it seems the remove member function isn't working or it's not picking up that there is a member missing . it doesn't appear in the members to remove [] in the log either.

**Comment by MarsssBlkm** [comment] 2020-02-20 03:54
@rosslutsch Yes I have met the same problem. By looking at the src/lib/worker.js, it seems like it only loops through pods, checking status and remove or add in db.

For scaling down isn't it gonna make more sense if by looping through mongo repset memebers, checking with alive pods and remove memebers in db..?

**Comment by MarsssBlkm** [comment] 2020-02-20 03:55
@rosslutsch I am new to k8s and node.js so I might be wrong, but I guess this doesn't look like a hard fix.

**Comment by MarsssBlkm** [comment] 2020-02-20 04:11
@rosslutsch 
I have met the same problem. It seems like the problem is with `inReplicaSet` function in `src/lib/worker.js`.
It only checks `if (member.state === 1)` while after scaling down the members which are supposed to be removed has `state == 8`.
I am new to k8s and node.js so I could be wrong..

**Comment by Zeedinstein** [comment] 2020-02-20 06:33
@rosslutsch and @MarsssBlkm I will have a look at this and see what I can do. Thanks for pointing out a starting place @MarsssBlkm. Not sure if they accepting pull requests at the moment but I will fork this on my side.

**Comment by jhughes2112** [comment] 2020-08-28 06:18
The issue with this was the parsing of the DateTime of the last heartbeat.  It was coming back NaN for me, at least.  I submitted a PR with fixes, and verified it was removing.  In the meantime, I've posted an image on DockerHub at jhughes2112/k8s-mongo-sidecar

**Comment by morphy2k** [comment] 2020-12-28 16:04
Sorry for the delay! Should be fixed with [v0.5.0](https://github.com/morphy2k/k8s-mongo-sidecar/releases/tag/v0.5.0)

**Closed by morphy2k** 2020-12-28 16:04 UTC
